#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# shellcheck disable=SC1091
source "$SCRIPT_DIR/lib/common.sh"

CONTAINER_OVERRIDE=""
COMMAND="build"
TARGET_DIR="$ROOT_DIR"

usage() {
    cat <<'EOF'
Usage: bash scripts/paper.sh [--target <dir>] [container_name] <build|biber|clean|open|print-config>
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --target)
            TARGET_DIR="$(abs_path "$2")"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        build|biber|clean|open|print-config)
            COMMAND="$1"
            shift
            break
            ;;
        *)
            CONTAINER_OVERRIDE="$1"
            shift
            if [[ $# -gt 0 ]]; then
                COMMAND="$1"
                shift
            fi
            break
            ;;
    esac
done

load_root_env "$TARGET_DIR"
load_paper_env "$TARGET_DIR"
[[ -n "$CONTAINER_OVERRIDE" ]] && CONTAINER_NAME="$CONTAINER_OVERRIDE"

stem="$(paper_entry_stem)"
container_build_dir="$(paper_container_build_dir)"
host_build_dir="$(paper_host_build_dir)"
entry_path="$PAPER_CONTAINER_DIR/$PAPER_ACTIVE_ENTRYPOINT"
out_flag=()
[[ -n "$PAPER_BUILD_DIR" ]] && out_flag+=("-output-directory=$PAPER_BUILD_DIR")

run_latex_pass() {
    docker exec "$CONTAINER_NAME" bash -lc "
        cd '$PAPER_CONTAINER_DIR'
        if [ -n '$PAPER_TEXINPUTS' ]; then
            export TEXINPUTS='$PAPER_TEXINPUTS'
        fi
        '$PAPER_LATEX_ENGINE' -interaction=nonstopmode -halt-on-error -file-line-error ${out_flag[*]} '$PAPER_ACTIVE_ENTRYPOINT'
    "
}

run_biber_pass() {
    docker exec "$CONTAINER_NAME" bash -lc "
        cd '$container_build_dir'
        biber '$stem'
    "
}

case "$COMMAND" in
    build)
        echo "→ active entrypoint: $PAPER_ACTIVE_ENTRYPOINT"
        echo "→ acceptance pdf:   $HOST_DIR/$PAPER_ACCEPT_PDF"
        run_latex_pass
        if [[ "$PAPER_RUN_BIBER" == "1" ]]; then
            if docker exec "$CONTAINER_NAME" bash -lc "test -f '$container_build_dir/$stem.bcf'"; then
                run_biber_pass
            else
                status_info "skipping biber because $stem.bcf was not generated by the current entrypoint"
            fi
        fi
        passes="$PAPER_BUILD_PASSES"
        while (( passes > 0 )); do
            run_latex_pass
            passes=$((passes - 1))
        done
        echo "→ host-visible pdf: $HOST_DIR/$PAPER_ACCEPT_PDF"
        ;;
    biber)
        run_biber_pass
        ;;
    clean)
        docker exec "$CONTAINER_NAME" bash -lc "
            cd '$container_build_dir'
            rm -f '$stem'.aux '$stem'.bbl '$stem'.bcf '$stem'.blg '$stem'.log '$stem'.out '$stem'.run.xml '$stem'.synctex.gz '$stem'.toc '$stem'.lof '$stem'.lot
        "
        ;;
    open)
        pdf_path="$HOST_DIR/$PAPER_ACCEPT_PDF"
        if [[ "$OSTYPE" == "darwin"* ]]; then
            open "$pdf_path" 2>/dev/null
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
            xdg-open "$pdf_path" 2>/dev/null || echo "请手动打开: $pdf_path"
        else
            echo "$pdf_path"
        fi
        ;;
    print-config)
        cat <<EOF
container=$CONTAINER_NAME
paper_dir=$PAPER_CONTAINER_DIR
entrypoint=$PAPER_ACTIVE_ENTRYPOINT
build_dir=${PAPER_BUILD_DIR:-<same as paper dir>}
latex_engine=$PAPER_LATEX_ENGINE
run_biber=$PAPER_RUN_BIBER
post_biber_passes=$PAPER_BUILD_PASSES
texinputs=${PAPER_TEXINPUTS:-<empty>}
accept_pdf=$PAPER_ACCEPT_PDF
accept_log=$PAPER_ACCEPT_LOG
accept_aux=$PAPER_ACCEPT_AUX
EOF
        ;;
    *)
        die "unknown paper command: $COMMAND"
        ;;
esac
